### ISSUE TITLE
unable to import ses-0.7.3 as ESM module

### ISSUE THREAD

**Issue by warner** [Agoric/SES-shim#229]
I know @kriskowal is playing whack-a-mole with the various ways to import SES, but I thought I'd add a few data points (and things which are thwarting my [attempts](https://github.com/agoric-labs/ses-adapter/) at implementing #216 "ses-adapter". All are using a `package.json` that depends on ses-0.7.3 and esm-3.2.25, and which lacks a `type:` property.

## ESM mode

`node t.mjs` on this:

```js
import { lockdown } from 'ses';
```

fails with:

```
/tmp/t$ node t.mjs
(node:24190) ExperimentalWarning: The ESM module loader is experimental.
(node:24190) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time
internal/modules/esm/resolve.js:58
  let url = moduleWrapResolve(specifier, parentURL);
            ^

Error: Cannot find main entry point for /tmp/t/node_modules/@agoric/make-hardener/ imported from /tmp/t/node_modules/ses/src/lockdown-shim.js
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:58:13)
    at Loader.resolve (internal/modules/esm/loader.js:85:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:188:40)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:42:40)
    at link (internal/modules/esm/module_job.js:41:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

## RESM (works)

`node -r esm t.js` on this:

```js
import { lockdown } from 'ses';
lockdown();
```

works as expected.

## CJS (works)

`node t.cjs` on this:

```js
const { lockdown } = require('ses');
lockdown();
```

works as expected.

**Comment by warner** [comment]
All three cases now work (against ses-0.7.6). Thanks!
