### ISSUE TITLE
intermittent failure in integration test

### ISSUE THREAD

**Issue by warner** [Agoric/SES-shim#245]
@erights and I noticed a transient failure in the integration test today, in https://github.com/Agoric/SES-shim/runs/528692397?check_suite_focus=true , under "integration test (13.x)", in the `Run yarn test:pre-release` step, it did:

```
Run cd packages/ses-integration-test && yarn test:pre-release
  cd packages/ses-integration-test && yarn test:pre-release
  shell: /bin/bash -e {0}
yarn run v1.22.0
$ node -r esm puppeteer-test/pre-release.test.js
TAP version 13
# SES works with mock unpkg umd
not ok 1 should not be equal
  ---
    operator: notEqual
    expected: undefined
    actual:   undefined
    stack: |-
      Error: should not be equal
          at Test.assert [as _assert] (/home/runner/work/SES-shim/SES-shim/node_modules/tape/lib/test.js:226:54)
          at Test.bound [as _assert] (/home/runner/work/SES-shim/SES-shim/node_modules/tape/lib/test.js:78:32)
          at Test.notEqual (/home/runner/work/SES-shim/SES-shim/node_modules/tape/lib/test.js:404:10)
          at Test.bound [as notEqual] (/home/runner/work/SES-shim/SES-shim/node_modules/tape/lib/test.js:78:32)
          at /home/runner/work/SES-shim/SES-shim/packages/ses-integration-test/puppeteer-test/utility/bundler.test.js:39:11
  ...
```

**Comment by warner** [comment]
It feels like this fails about 50% of the time. Hitting the "rebuild" button makes it go away.

I've seen a different test fail sometimes (test 7, I think).

**Comment by kriskowal** [comment]
The parcel test flaps too. Thanks for tracking.

**Comment by kriskowal** [comment]
I have not seen this in months. Closing to waken Murphy’s Law.
