### ISSUE TITLE
'tap' wants to modify Error.stackTraceLimit, fails under SES

### ISSUE THREAD

**Issue by warner** [Agoric/SES-shim#247]
I'm trying to use `tap` to run unit tests in agoric-swingset, under SES (with `noTameError: true` right now), inside the "start compartment". If an Error is thrown inside a Promise callback, the `tap` error-printing code attempts to temporarily modify `Error.stackTraceLimit`, which of course fails because `Error` is hardened.

The troublesome code is in the `stack-utils` package, inside `index.js` around line 102 and 109:

```js
StackUtils.prototype.captureString = function (limit, fn) {
  if (typeof limit === 'function') {
    fn = limit;
    limit = Infinity;
  }
  if (!fn) {
    fn = this.captureString;
  }

  var limitBefore = Error.stackTraceLimit;
  if (limit) {
    Error.stackTraceLimit = limit;
  }

  var obj = {};

  Error.captureStackTrace(obj, fn);
  var stack = obj.stack;
  Error.stackTraceLimit = limitBefore;

  return this.clean(stack);
};
```

With this in place, tap explodes when it attempts to report a test failure in my code (and it does not get a chance to report any of the successes):

```
$ yarn test
yarn run v1.22.4
$ tap --no-coverage --reporter specy test/**/test*.js
test/test-ses.js 2>
test/test-ses.js 2> /home/warner/stuff/agoric/agoric-sdk/node_modules/stack-utils/index.js:102
test/test-ses.js 2>     Error.stackTraceLimit = limit;
test/test-ses.js 2>                           ^
test/test-ses.js 2> /home/warner/stuff/agoric/agoric-sdk/node_modules/stack-utils/index.js:1
test/test-ses.js 2> TypeError: Cannot assign to read only property 'stackTraceLimit' of function 'function Error() { [native code] }'
test/test-ses.js 2>     at StackUtils.captureString (/home/warner/stuff/agoric/agoric-sdk/node_modules/stack-utils/index.js:102:27)
test/test-ses.js 2>     at TAP.sub (/home/warner/stuff/agoric/agoric-sdk/node_modules/tap/lib/test.js:240:25)
test/test-ses.js 2>     at TAP.test (/home/warner/stuff/agoric/agoric-sdk/node_modules/tap/lib/test.js:274:17)
test/test-ses.js 2>     at Object.<anonymous> (/home/warner/stuff/agoric/agoric-sdk/packages/import-bundle/test/do-import.js:30:5)
test/test-ses.js 2>     at Generator.next (<anonymous>)
test/test-ses.js 2>     at Object.<anonymous> (/home/warner/stuff/agoric/agoric-sdk/packages/import-bundle/test/test-ses.js:1)
test/test-ses.js 2>     at Generator.next (<anonymous>)
test/test-ses.js
```

If I comment those `Error.stackTraceLimit = ` lines out, my test's actual error is revealed:

```
$ yarn test
yarn run v1.22.4
$ tap --no-coverage --reporter specy test/**/test*.js
test/test-ses.js 1> go
test/test-ses.js
  test import
    ✖ added is not defined

      stack: |
        Object.f4 (test/bundle1.js:24:23)
        testBundle1 (test/do-import.js:26:17)
        async Test.testImport (test/do-import.js:41:3)
      at:
        line: 24
        column: 23
        file: test/bundle1.js
        function: Object.f4
      type: ReferenceError
      tapCaught: returnedPromiseRejection
      test: test import

  ✓ ns1.f1 getExport ok
  ✓ ns1.f2 getExport ok
  ✓ ns2.f1 getExport ok
  ✓ ns2.f2 getExport ok
  ✓ ns2.f3 getExport ok
```

I don't know what we can do about this, but I'm collecting a list of libraries that misbehave when run under SES in the hopes we can tame them or find a workaround.

**Comment by erights** [comment]
Assigned it to myself. Work already started at https://github.com/Agoric/SES-shim/pull/11 + https://github.com/Agoric/SES-shim/tree/delta-tame-error . If there are no surprises, I can complete this.

**Comment by warner** [comment]
closing this as a duplicate of #8
