### ISSUE TITLE
Babel dependency limits module system support

### ISSUE THREAD

**Issue by kriskowal** [Agoric/SES-shim#268]
Per #257, the `ses` package will need to entrain a dependency on `@agoric/transform-module` and consequently `@babel/core`. This new dependency would seem to limit SES to supporting only ECMAScript modules (ESM) since there doesn’t appear to be an import form for `@babel/core` that works for `node -r esm` or CommonJS, much less a form that works for all possible uses.

```js
import * as babelCore from '@babel/core';
// ✅ ESM ❌ RESM ❌ CJS
```

CJS output shows a `require` error in the CJS code translated by Rollup:

```
internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module './transformation/file/file'
Require stack:
- /Users/kris/ses/packages/ses/dist/ses.cjs
- /Users/kris/ses/packages/ses/test/package/test.cjs
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/kris/ses/packages/ses/dist/ses.cjs:4360:36)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/kris/ses/packages/ses/dist/ses.cjs',
    '/Users/kris/ses/packages/ses/test/package/test.cjs'
  ]
}
```

The symptom is similar for `node -r esm`:

```
Error: Cannot find module './transformation/file/file'
Require stack:
- /Users/kris/ses/packages/ses/dist/ses.cjs
- /Users/kris/ses/packages/ses/test/package/test.js
    at Object.<anonymous> (/Users/kris/ses/packages/ses/dist/ses.cjs:4360:36)
    at Object.<anonymous> (/Users/kris/ses/packages/ses/dist/ses.cjs:1) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/kris/ses/packages/ses/dist/ses.cjs',
    '/Users/kris/ses/packages/ses/test/package/test.js'
  ]
}
```

```js
import babelCore from '@babel/core';
// ✅ ESM ❌ RESM ❌ CJS (Does not Roll Up)

```js
import { transformSync, transformFromAstSync } from '@babel/core';
const babelCore = { transformSync, transformFromAstSync };
// ❌ ESM (names not exported) ❌ RESM ❌ CJS (Does not Roll Up)
```

**Comment by kriskowal** [comment]
The `require("./transformation/file/file")` originates in `@babel/core` in `lib/index.js`.

**Comment by kriskowal** [comment]
@michaelfig and I overcame this limitation, at least for a while, by using Michael’s fork of Babel at https://github.com/agoric-labs/babel to publish a version of `@agoric/babel-standalone` that did not include the packages that interfere with SES.

It was also necessary to update the Rollup configuration in the ses-integration-test to ensure that it subsumed the additional SES dependencies including `@agoric/babel-standalone`.

The build process works now but produces warnings that `@agoric/babel-standalone` has no `default` export. For whatever reason, we can’t use ESM default import syntax to get it, and have to extract the `default` property from the module exports namespace ourselves.

So, enough has been written to get us beyond this hurdle, but we can expect a sequel.
