### ISSUE TITLE
unable to use 'bindings' module after lockdown (used by node-lmdb)

### ISSUE THREAD

**Issue by warner** [Agoric/SES-shim#308]
When `install-ses.js` is a file that imports SES-0.7.7 and calls `lockdown()`, the following program:

```js
import './install-ses.js';
import lmdb from 'node-lmdb';
```

fails like:

```
$ node -r esm t.js
/home/warner/stuff/agoric/agoric-sdk/node_modules/bindings/bindings.js:1
TypeError: Cannot read property 'indexOf' of undefined
    at Function.getFileName (/home/warner/stuff/agoric/agoric-sdk/node_modules/bindings/bindings.js:178:16)
    at bindings (/home/warner/stuff/agoric/agoric-sdk/node_modules/bindings/bindings.js:82:48)
    at Object.<anonymous> (/home/warner/stuff/agoric/agoric-sdk/node_modules/node-lmdb/index.js:3:37)
    at Generator.next (<anonymous>)
    at Object.<anonymous> (/home/warner/stuff/agoric/agoric-sdk/packages/swing-store-lmdb/t.js:1)
    at Generator.next (<anonymous>)
```

The core problem seems to be the [`bindings`](https://www.npmjs.com/package/bindings) module used by `node-lmdb`, which modifies `Error` to learn the filename of the invoking module (and leverage that to find the DLL/.so that needs to be imported):

```js
exports.getFileName = function getFileName(calling_file) {
  var origPST = Error.prepareStackTrace,
    origSTL = Error.stackTraceLimit,
    dummy = {},
    fileName;

  Error.stackTraceLimit = 10;

  Error.prepareStackTrace = function(e, st) {
    for (var i = 0, l = st.length; i < l; i++) {
      fileName = st[i].getFileName();
      if (fileName !== __filename) {
        if (calling_file) {
          if (fileName !== calling_file) {
            return;
          }
        } else {
          return;
        }
      }
    }
  };

  // run the 'prepareStackTrace' function above
  Error.captureStackTrace(dummy);
  dummy.stack;

  // cleanup
  Error.prepareStackTrace = origPST;
  Error.stackTraceLimit = origSTL;

  // handle filename that starts with "file://"
  var fileSchema = 'file://';
  if (fileName.indexOf(fileSchema) === 0) {
    fileName = fileURLToPath(fileName);
  }

  return fileName;
};
```

The error is due to `fileName` being undefined, probably because `prepareStackTrace` was not successfully overridden. Calling `lockdown()` with `noTameError: true` doesn't help.

**Comment by warner** [comment]
For LMDB, one workaround is to `import 'node-lmdb'` (for side-effects only, no imported names) before `install-ses`, then let the normal code import it again afterwards. It looks like the DLL is located (and maybe loaded) the first time it gets imported. This still falls into the "vetted shim" category, but it's at least a functional workaround.

**Comment by warner** [comment]
This is an instance of #251, closing in favor of the other ticket.
